
services:
  db:
    image: postgres:15-alpine
    container_name: artrari-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: artrari
    ports:
      - "5433:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: artrari-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/artrari
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      CLOUDINARY_URL: "cloudinary://585674141627634:dLa7raVu71BJTk8gayyu_nCqYHA@daxiid35t"

volumes:
  pgdata:
