spring.application.name=ArtRari

spring.datasource.url=jdbc:postgresql://localhost:5432/artrari
spring.datasource.username=postgres
spring.datasource.password=1234009
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expirationMs=14400000

app.pagination.default-size=12

spring.profiles.include=local

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server.port=8080